import { Request, Response, NextFunction } from "express";
import ValidationError from "../errors/validationError";
import EntityNotFoundError from "../errors/entityNotFoundError";
import InternalServerError from "../errors/internalServerError";

const getErrorMessage = (error: unknown): string => {
  if (
    error instanceof Error ||
    error instanceof ValidationError ||
    error instanceof EntityNotFoundError ||
    error instanceof InternalServerError
  ) {
    return error.message;
  }
  if (error && typeof error === "object" && "message" in error) {
    return String(error.message).toString();
  }
  if (typeof error === "string") {
    return error;
  }
  if (error instanceof String) {
    return error.toString();
  }
  return "An unknown error occured";
};

// Handling database errors generated by mongoose.
export const databaseErrorHandler = (
  error: unknown,
  _req: Request,
  res: Response,
  next: NextFunction
) => {
  // Checking if error was a duplicate booking error
  if (
    error instanceof Error &&
    error.message.startsWith("E11000 duplicate key error collection")
  ) {
    // Rendering appointment date selection page.
    res.status(409).render("selectDate");
    // Checking if the error was raised due to error in field validation
  } else if (
    error instanceof Error &&
    error.message.startsWith("Appointment validation failed")
  ) {
    res.status(409).render("error", {
      errorValues: { message: getErrorMessage(error.message) }
    });
  } else {
    next(error);
  }
};

// Handling errors of all classes
export const generalErrorHandler = (
  error: unknown,
  _req: Request,
  res: Response,
  next: NextFunction
) => {
  if (error instanceof EntityNotFoundError) {
    res
      .status(error.statusCode)
      .render("error", { errorValues: { message: getErrorMessage(error) } });
  } else if (error instanceof ValidationError) {
    res
      .status(error.statusCode)
      .render("error", { errorValues: { message: getErrorMessage(error) } });
  } else if (error instanceof Error) {
    res.status(500).render("error", {
      errorValues: { message: `${error.message}` }
    });
  } else if (error instanceof InternalServerError) {
    res.status(error.statusCode).render("error", {
      errorValues: { message: getErrorMessage(error.message) }
    });
  } else {
    next(error);
  }
};

export const unknownEndPoint = (_req: Request, res: Response) => {
  // We will render an page not found here.
  res
    .status(404)
    .render("error", { errorValues: { message: "This is an unknown route" } });
};
